---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "gitlab.praktikum-services.ru:5050/std-025-75/sausage-store/sausage-backend:latest"
          ports:
            - name: backend
              containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              value: $SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: $SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              value: $SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              value: $SPRING_DATA_MONGODB_URI
            - name: REPORT_PATH
              value: "/var/sausage-store/reports/"
      imagePullSecrets:
        - name: docker-config-secret