---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  revisionHistoryLimit: 12
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{.Values.backend.image}}
          ports:
            - name: backend
              containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: ss-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ss-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ss-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: ss-secrets
                  key: SPRING_DATA_MONGODB_URI
            - name: REPORT_PATH
              value: "/var/sausage-store/reports/"
      imagePullSecrets:
        - name: docker-config-secret