stages:
  - deploy

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
  environment:
    name: sausage-store
    url: https://tyutyunov-igor-025.k8s.praktikum-services.tech
  rules:
    - when: manual
  script:
    - export KUBECONFIG=$KUBE_CONFIG
    - kubectl config get-contexts
