---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: "gitlab.praktikum-services.ru:5050/std-025-75/sausage-store/sausage-backend-report:latest"
          ports:
            - name: backend-report
              containerPort: 80
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://std-025-75:Testusr1234@rc1d-373rb11d8uq2e4b5.mdb.yandexcloud.net:27018/std-025-75?tls=true"
      imagePullSecrets:
        - name: docker-config-secret